Add type definition for push
oursky/ts-skygear pull request #6
Opened 2018-10-12 08:08 UTC by MarkRunWu

2018-10-12 10:26 UTC, louischan-oursky requested changes
@MarkRunWu

2018-10-12 10:26 UTC, louischan-oursky commented on index.d.ts
> +    unregisterDevice(): Promise<string>;
The return type should be `Promise<void>`

2018-10-12 10:26 UTC, louischan-oursky commented on index.d.ts
> +      users: string[],
`users: string | string[],`

2018-10-12 10:26 UTC, louischan-oursky commented on index.d.ts
> +      topic: string
`topic?: string`

2018-10-12 10:26 UTC, louischan-oursky commented on index.d.ts
> +    ): Promise<KVObject>;
I think the return type is better to be `Promise<void>` because the actual return type is not very useful.

2018-10-12 10:26 UTC, louischan-oursky commented on index.d.ts
> +      devices: string[],
`devices: string | string[],`

2018-10-12 10:26 UTC, louischan-oursky commented on index.d.ts
> +      topic: string
`topic?: string`

2018-10-12 10:26 UTC, louischan-oursky commented on index.d.ts
> +    ): Promise<KVObject>;
Return type is better to be `Promise<void>`

2018-10-12 10:56 UTC, MarkRunWu commented
@louischan-oursky Updated.

2018-10-15 03:16 UTC, louischan-oursky approved these changes

2018-10-15 03:16 UTC, louischan-oursky commented
Thanks!

2018-10-15 03:19 UTC, merged

2018-10-15 03:36 UTC, louischan-oursky commented
@MarkRunWu I updated the installation of this package.

https://github.com/oursky/ts-skygear

Can you try it?

2018-10-15 03:41 UTC, MarkRunWu commented
Ok, thanks